# https://taskfile.dev

version: '3'

dotenv: ['.env']

vars:
  migrations_path: ./migrations

env:
  SSO_CONFIG_PATH: ./config/config.yaml

tasks:
  migrationsUp:
    cmds:
      - go run ./cmd/migrator --migrationsPath={{.migrations_path}}
    silent: true
  migrationsDown:
    cmds:
      - go run ./cmd/migrator --migrationsPath={{.migrations_path}} --direction=down
    silent: true
  ssoServiceUp:
    cmds:
      - go run ./cmd/sso
    deps:
      - task: migrationsUp
  test:
    cmds:
      - go test ./...
