ALTER TABLE permissions
    ALTER COLUMN id TYPE INTEGER,
    ALTER COLUMN user_id TYPE INTEGER,
    ALTER COLUMN app_id TYPE INTEGER;
ALTER TABLE apps ALTER COLUMN id TYPE INTEGER;
ALTER TABLE users ALTER COLUMN id TYPE INTEGER;
ALTER SEQUENCE permissions_id_seq AS INTEGER;
ALTER SEQUENCE apps_id_seq AS INTEGER;
ALTER SEQUENCE users_id_seq AS INTEGER;

CREATE INDEX IF NOT EXISTS idx_email ON users (email);

ALTER TABLE permissions
    DROP CONSTRAINT IF EXISTS permissions_user_app_unique,
    ALTER COLUMN user_id DROP NOT NULL,
    ALTER COLUMN app_id DROP NOT NULL;
